basePath: /api/v1
definitions:
  handler.CreateLinkRequest:
    properties:
      expires_at:
        type: string
      long_url:
        maxLength: 20448
        type: string
    required:
    - long_url
    type: object
  handler.CreateLinkResponse:
    properties:
      data:
        $ref: '#/definitions/handler.LinkSample'
      message:
        example: Link created successfully!
        type: string
      status:
        example: true
        type: boolean
    type: object
  handler.GetLinkResponse:
    properties:
      data:
        $ref: '#/definitions/handler.LinkSample'
      message:
        example: Records fetched successfully!
        type: string
      status:
        example: true
        type: boolean
    type: object
  handler.GetLinksResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/handler.LinkSample'
        type: array
      message:
        example: Link created successfully!
        type: string
      status:
        example: true
        type: boolean
    type: object
  handler.HealthResponse:
    properties:
      message:
        example: "\U0001F4AA Shortener API is up and running!"
        type: string
      status:
        example: true
        type: boolean
    type: object
  handler.LinkSample:
    properties:
      clicks:
        example: 10
        type: integer
      created_at:
        example: "2026-02-02T00:00:00Z"
        type: string
      expires_at:
        example: "2027-04-08T00:00:00Z"
        type: string
      id:
        example: 1
        type: integer
      long_url:
        example: https://facebook.com
        type: string
      short_code:
        example: "1234567890"
        type: string
      updated_at:
        example: "2026-09-11T00:00:00Z"
        type: string
    type: object
  handler.UpdateLinkRequest:
    properties:
      expires_at:
        type: string
      long_url:
        maxLength: 2048
        type: string
    type: object
  handler.UpdateLinkResponse:
    properties:
      data:
        $ref: '#/definitions/handler.LinkSample'
      message:
        example: Link updated successfully!
        type: string
      status:
        example: true
        type: boolean
    type: object
host: localhost:8003
info:
  contact:
    email: promiseihunna@gmail.com
    name: Promise
  description: API for creating and resolving shortened URLs.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: URL Shortener
  version: "1.0"
paths:
  /health:
    get:
      description: Returns the health status of the shortener API.
      operationId: healthCheck
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.HealthResponse'
      summary: Health check
      tags:
      - health
  /links:
    get:
      description: Fetch all links record
      parameters:
      - description: limit pagination records
        in: query
        name: limit
        type: string
      - description: specify pagination page
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.GetLinksResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get links
      tags:
      - links
    post:
      consumes:
      - application/json
      description: Create new shortened URL
      parameters:
      - description: Create Link payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateLinkRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.CreateLinkResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Shorten URL
      tags:
      - links
  /links/{id}:
    delete:
      description: Delete link by id
      parameters:
      - description: Link ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete link
      tags:
      - links
    get:
      description: Fetch link by id
      parameters:
      - description: Link ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GetLinkResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get link
      tags:
      - links
    patch:
      consumes:
      - application/json
      description: Update link by id
      parameters:
      - description: Link id
        in: path
        name: id
        required: true
        type: integer
      - description: Fields to update
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateLinkRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.UpdateLinkResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update link
      tags:
      - links
schemes:
- http
swagger: "2.0"
